# Generated by Django 3.1.3 on 2021-11-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masterpiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.JSONField()),
                ('artist', models.CharField(max_length=10)),
                ('flag_count', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('like_count', models.IntegerField(default=0)),
                ('liked_by', models.TextField()),
            ],
        ),
    ]
